apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-guestbook-dev
  namespace: example
spec:
  project: example

  source:
    repoURL: "https://github.com/argoproj/argocd-example-apps.git"
    targetRevision: HEAD
    path: guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: example-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
